before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - files:
      - share/man/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  - name: circumflex
    repository:
      owner: bensadeh
      name: homebrew-circumflex
    description: "circumflex is a command line tool for browsing Hacker News in your terminal"
    homepage: "https://github.com/bensadeh/circumflex/"
    license: "AGPL-3.0-only"
    dependencies:
      - name: less
    install: |
      bin.install "circumflex" => "clx"
      man1.install "#{buildpath}/share/man/clx.1"
