before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  - name: circumflex
    tap:
      owner: bensadeh
      name: homebrew-circumflex
    description: "circumflex is Hacker News in your terminal"
    homepage: "https://github.com/bensadeh/circumflex/"
    license: "AGPL-3.0-only"
    install: |
      bin.install "circumflex" => "clx"
