before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      386: 32-bit
      amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  - name: circumflex
    tap:
      owner: bensadeh
      name: homebrew-circumflex
    description: "circumflex is a command line tool for browsing Hacker News in your terminal"
    homepage: "https://github.com/bensadeh/circumflex/"
    license: "AGPL-3.0-only"
    dependencies:
      - name: less
    install: |
      bin.install "circumflex" => "clx"
      man.install "share/man/"
